#!/usr/bin/R
# Runs DADA2 pipeline on a set of 16S rRNA gene, 2x250bp, in three samples: one Healthy donor ("Healthy"), one Irritable Bowel Syndrome with Constipation ("IBSC"), and one Irritable Bowel Syndrome with Diarrhea ("IBSD"), for the session "Microbiome 1".
#BiocManager::install("dada2")
library("dada2")
options(witdh=140)

baseDir <- paste0(getwd(), "/microbiomas/")
list.files(baseDir)
# directory containing the fastq files after unzipping.
inputDir <- paste0(baseDir, "inputFQfiles/")
# These fastq files were generated by 2x250 Illumina Miseq amplicon sequencing of the V4 region of the 16S rRNA gene from stool samples collected from a Healthy donor, an IBS-C patient and IBS-D. 
# List the paired-end fastq files will be processed with the DADA2 pipeline. These files are compressed, but DADA2 can work with gzipped files
list.files(inputDir)

# Define fastq filenames Forward and Reverse with the following format: Samplename_F.fastq and Samplename_R.fastq (Forward read and Reverse read, respectively)
fnFs <- sort(list.files(inputDir, pattern="_F.fq.gz", full.names=TRUE))
fnRs <- sort(list.files(inputDir, pattern="_R.fq.gz", full.names=TRUE))

# Extract sample names, assuming filenames have format: SAMPLENAME_XXX.fastq
sample.names <- sapply(strsplit(basename(fnFs), "_"), `[`, 1)

# Inspect read quality profiles. 
# We start by visualizing the quality profiles of the forward reads:
plotQualityProfile(fnFs[1:3])
# Now we visualize the quality profile of the reverse reads:
plotQualityProfile(fnRs[1:3])

# trimming as the average qualities crash will improve the algorithm’s sensitivity to rare sequence variants. Based on these profiles, we will truncate the reverse reads at position 160 where the quality distribution crashes.

# Place filtered files in filtered subdirectory
filtFs <- file.path(inputDir, "filtered", paste0(sample.names, "_F_filt.fq.gz"))
filtRs <- file.path(inputDir, "filtered", paste0(sample.names, "_R_filt.fq.gz"))
names(filtFs) <- sample.names
names(filtRs) <- sample.names

# Filter and trim reads. We’ll use standard filtering parameters: maxN=0 (DADA2 requires no Ns), truncQ=2, rm.phix=TRUE and maxEE=2. The maxEE parameter sets the maximum number of “expected errors” allowed in a read
table_filtered <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen=c(240,160), maxN=0, maxEE=c(2,2), truncQ=2, rm.phix=TRUE, compress=TRUE, multithread=TRUE, verbose=TRUE) 
table_filtered

# Inspect the proportion of filtered reads remaining
100*table_filtered[,"reads.out"] / table_filtered[,"reads.in"]
plot(x=table_filtered[,"reads.in"], y=table_filtered[,"reads.out"], xlab="Starting reads (reads in)", ylab="Remaining reads (reads out)", main="Filter and trim process", col="dodgerblue", pch=16)
abline(lm(table_filtered[,"reads.out"] ~ table_filtered[,"reads.in"]), col="coral")

# Learn the Error Rates: The DADA2 algorithm makes use of a parametric error model (err) and every amplicon dataset has a different set of error rates.

errF <- learnErrors(filtFs, multithread=TRUE, verbose=TRUE)
head(errF)

errR <- learnErrors(filtRs, multithread=TRUE, verbose=TRUE, MAX_CONSIST=20) 
# If we use the default, MAX_CONSIST=10, it will launch the message: Self-consistency loop terminated before convergence, so we increase a little the MAX_CONSIST parameter

head(errR)

# visualize the estimated error rates, first in the Fw, then in the Rv:
plotErrors(errF, nominalQ=TRUE)
plotErrors(errR, nominalQ=TRUE)

# Sample Inference. 
# We are now ready to apply the core sample inference algorithm to the filtered and trimmed sequence data
dadaFs <- dada(filtFs, err=errF, multithread=TRUE, verbose=TRUE)
# this produces a dada-class object describing DADA2 denoising results. 

# Sample inference (ASV inference) in the filtered and trimmed Reverse reads
dadaRs <- dada(filtRs, err=errR, multithread=TRUE, verbose=TRUE)

for (sample in sample.names) {
  print(sample)
  print(dadaFs[[sample]])
  print(dadaRs[[sample]])
  writeLines("")
}

# Merge paired reads
# We now merge the forward and reverse reads together to obtain the full denoised sequences
mergers <- mergePairs(dadaFs, filtFs, dadaRs, filtRs, verbose=TRUE)
# Inspect the merger data.frame from the 3 samples
head(mergers[["Healthy"]])
head(mergers[["IBSC"]])
head(mergers[["IBSD"]])


# Construct sequence table
# We can now construct an Amplicon Sequence Variant table (ASV) table, a higher-resolution version of the OTU table produced by traditional methods.
seqtab <- makeSequenceTable(mergers)
dim(seqtab)	# 3 samples, 1352 ASVs

# Inspect distribution of sequence lengths and plot histogram
table(nchar(getSequences(seqtab)))
hist(nchar(getSequences(seqtab)), main="Distribution of sequence lengths", col="coral", xlab="seq length", breaks=seq(288,294))

# Remove chimeras. Most of our reads should remain after chimera removal
seqtab.nochim <- removeBimeraDenovo(seqtab, method="consensus", multithread=TRUE, verbose=TRUE)
# The fraction of chimeras varies based on factors including experimental procedures and sample complexity, but can be substantial. Here chimeras make up about 67% of the inferred sequence variants.
dim(seqtab.nochim)
# Proportion between reads without chimeras and starting reads
sum(seqtab.nochim)/sum(seqtab)
# Chimeras account for about 44% of the total sequence reads (probably because it is a simulated dataset, or because we have not trimmed the primers). 
# Most of our reads should remain after chimera removal. If most of your reads were removed as chimeric, upstream processing may need to be revisited. In almost all cases this is caused by primer sequences with ambiguous nucleotides that were not removed prior to beginning the DADA2 pipeline.

# Track reads through the pipeline
# As a final check of our progress, we’ll look at the number of reads that made it through each step in the pipeline:
getN <- function(x) sum(getUniques(x))
track <- cbind(table_filtered, sapply(dadaFs, getN), sapply(dadaRs, getN), sapply(mergers, getN), rowSums(seqtab.nochim))

colnames(track) <- c("input", "filtered", "denoisedF", "denoisedR", "merged", "nonchim")
rownames(track) <- sample.names
head(track)

# Assign taxonomy to the sequence variants. The DADA2 package provides a native implementation of the naive Bayesian classifier method for this purpose. SilvaDB is a very good reference database for both the Small Subunit and Large Subunit of ribosomes of all Kingdoms, but unfortunately it requires a lot of free RAM to run in a laptop computer. We will use RDP, the Ribosomal Database Project's Training Set 18 
# assignedTaxa <- assignTaxonomy(seqtab.nochim, paste0(baseDir, "/silvaDB/","silva_nr99_v138.1_wSpecies_train_set.fa.gz"), multithread=TRUE)
# assignedTaxa <- addSpecies(assignedTaxa, paste0(baseDir, "/silvaDB/silva_species_assignment_v138.1.fa.gz"))    # assign species
assignedTaxa <- assignTaxonomy(seqtab.nochim, paste0(baseDir, "/dbs/RDP/rdp_train_set_18.fa.gz"), multithread=FALSE) # classifies until genus
assignedTaxa <- addSpecies(assignedTaxa, paste0(baseDir, "/dbs/RDP/rdp_species_assignment_18.fa.gz"))    # assign species

# Let’s inspect the taxonomic assignments:
taxa.print <- assignedTaxa # Removing sequence rownames for display only
rownames(taxa.print) <- NULL
head(taxa.print)

# Count sequences and add to global table without the sequence itself
transposed_seqtab <- t(seqtab.nochim)
countedTaxa <- matrix(nrow=dim(seqtab.nochim)[2], ncol=(dim(seqtab.nochim)[1]+7)) # Kingdom Phylum Class Order Family Genus Species
colnames(countedTaxa) <- c(colnames(transposed_seqtab), colnames(assignedTaxa))

for (sequence in 1:dim(seqtab.nochim)[2] ){
  countedTaxa[sequence,] <- c(as.character(transposed_seqtab[sequence,]), as.character(assignedTaxa[sequence,]))
} 
write.table(countedTaxa, file=paste0(baseDir,"/counts_16S_RDP.tsv"), quote=FALSE, col.names=NA, sep="\t")
write.table(cbind(countedTaxa, rownames(assignedTaxa)), file=paste0(baseDir,"/counts_s16S_sequences_RDP.tsv"), quote=FALSE, col.names=NA, sep="\t")

# use phyloseq to calculate biodiversity indices, and barplots, plot Exploratory Heat Maps...
BiocManager::install("phyloseq")
library("phyloseq")
library("ggplot2")

samples.out <- data.frame(Disease=c("Healthy","IBS-C","IBS-D")) # there is possibility to include other metadata in this data frame, as sex, age, diet...
rownames(samples.out) = rownames(seqtab.nochim)

# Create phyloseq-class experiment-level object
ps <- phyloseq(otu_table(seqtab.nochim, taxa_are_rows=FALSE), sample_data(samples.out), tax_table(assignedTaxa))

# Plot the species richness
plot_richness(ps, x="Disease", measures=c("Fisher", "Shannon", "Simpson", "Chao1"), color="Disease") + theme_bw()

# Create Bar plots: we take the 50 most abundant taxa to improve visualization
top_ASVs <- names(sort(taxa_sums(ps), decreasing=TRUE))[1:50]
ps.top_ASVs <- transform_sample_counts(ps, function(OTU) OTU/sum(OTU))
ps.top_ASVs <- prune_taxa(top_ASVs, ps.top_ASVs)

# Plot the Relative Abundances (Phylum level)
plot_bar(ps.top_ASVs, x="Disease", fill="Phylum") + facet_wrap(~Disease, scales="free_x")

# Plot the Relative Abundances (Class level)
plot_bar(ps.top_ASVs, x="Disease", fill="Class") + facet_wrap(~Disease, scales="free_x")

# Plot the Relative Abundances (Order level)
plot_bar(ps.top_ASVs, x="Disease", fill="Order") + facet_wrap(~Disease, scales="free_x")

# Plot the Relative Abundances (Family level)
plot_bar(ps.top_ASVs, x="Disease", fill="Family") + facet_wrap(~Disease, scales="free_x")

# For home plot the abundances at Genus and Species. At which level do you see better the differences between the Irritable Bowel Syndrome and the normal? Do you observe diferences in the type "C" and "D" IB syndromes?

# Heatmap Plots
# First rename the sequences for ASV order, to improve visualization (sequences are very long)
taxa_names(ps) <- paste("ASV-", 1:dim(otu_table(ps))[2], sep="")

# Heatmap of Kingdom Bacteria
Kingdom_ps <- subset_taxa(ps, Kingdom=="Bacteria")
Kingdom_ps <- prune_taxa(names(sort(taxa_sums(Kingdom_ps),TRUE)[1:20]), Kingdom_ps)
plot_heatmap(Kingdom_ps, sample.label="Disease", "NMDS", "bray", "Phylum", low="#000033", high="#FF3300")

# Heatmap of Family Lachnospiraceae
Family_ps <- subset_taxa(ps, Family=="Lachnospiraceae")
Family_ps <- prune_taxa(names(sort(taxa_sums(Family_ps),TRUE)[1:30]), Family_ps)
plot_heatmap(Family_ps, sample.label="Disease", "NMDS", "bray", "Genus", low="#000033", high="#FF3300")

# Heatmap of genus Bacteroides
Genus_ps <- subset_taxa(ps, Genus=="Alistipes")
Genus_ps <- prune_taxa(names(sort(taxa_sums(Genus_ps),TRUE)[1:30]), Genus_ps)
plot_heatmap(Genus_ps, sample.label="Disease", "NMDS", "bray", "Species", low="#000033", high="#FF3300")


# Remember these phyloseq functions because although in the Metagenomics session we will not use them, there will be homework :-)
